import { NextPage } from "next"
import Head from "next/head"

const aboutus: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Danny's Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1 className="text-3xl font-bold underline">
         About us
        </h1>
      </div>
    )
  }
  
  export default aboutus
  