import type { NextPage } from 'next'
import Head from 'next/head'
import ArticleList from '../components/ArticleList';


export interface IArticles {
  userId: number;
  id: number;
  title: string;
  body: string;
}


const Home: NextPage = ({ articles }: any) => {
  console.log(articles)
  return (
    <div>
      <Head>
        <title>Danny's Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1> */}
      <ArticleList articles={articles} />


    </div>
  )
}

export default Home
export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`)
  const articles = await res.json()

  return {
    props: {
      articles,
    },
  }
}
